/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119444-g2b6303762f-20250506"
#endif /* AVUTIL_FFVERSION_H */
